version: "3.9"

services:

  pokemon_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/app/
      - ./timezone/localtime:/etc/localtime
      - ./timezone/timezone:/etc/timezone
      - ./logs/:/usr/app/logs/
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data:delegated

volumes:
  esdata:
    driver: local

